import axios from 'axios';
import { Booking, BookingInput, ReportRow, Station } from './types';
import { createLocalBooking, deleteLocalBooking, getLocalBookings, getLocalStationReport, getLocalStations, getLocalUserReport } from './localApi';
const api = axios.create({ baseURL: import.meta.env.VITE_API_URL ?? 'http://localhost:5000/api' });
const local = import.meta.env.VITE_DESKTOP === '1';
export const getStations = () => local ? getLocalStations() : api.get<Station[]>('/stations').then(r => r.data);
export const getBookings = () => local ? getLocalBookings() : api.get<Booking[]>('/bookings').then(r => r.data);
export const createBooking = (input: BookingInput) => local ? createLocalBooking(input) : api.post<Booking>('/bookings', input).then(r => r.data);
export const deleteBooking = (id: number) => local ? deleteLocalBooking(id) : api.delete(`/bookings/${id}`);
export const getUserReport = () => local ? getLocalUserReport() : api.get<ReportRow[]>('/reports/users').then(r => r.data);
export const getStationReport = () => local ? getLocalStationReport() : api.get<ReportRow[]>('/reports/stations').then(r => r.data);
